name: "Deploy web"

on:
  push:
    paths:
      - "web/**"
    branches: ["main"]
  pull_request:
    paths:
      - "web/**"
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./web
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: "canary"
      - name: Check web cache
        uses: actions/cache@main
        with:
          path: |
            web/.next/cache
          key: ${{ runner.os }}-web-nextjs-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-web-nextjs-${{ hashFiles('**/package.json') }}
      - name: Install deps
        run: bun i
      - name: Build web
        run: bun run build
      - name: Deploy web
        uses: cloudflare/pages-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lucasquinn
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web
          wranglerVersion: "beta"
